### PR TITLE
Pure cmake

### PR DESCRIPTION
**Pull request by Levi-Armstrong**

### CODE REVIEW

**Comment by Levi-Armstrong** [comment]
@gavanderhoorn This fixes it. It looks like the method I used does not work with interface targets. I reverted to using the compiler option.

**Comment by Levi-Armstrong** [comment]
@haudren Do you mind testing this PR?

**Comment by haudren** [comment]
Just tested on a 16.04 system, build is fine :)

**Comment by Levi-Armstrong** [comment]
@gavanderhoorn  I had to make some changes for this to build and run tests. I added a check for GTest and if it does not exist I use ExternalProject_add to clone it down and build it as part of the project. Let me know if you have any concerns.

https://travis-ci.org/Levi-Armstrong/opw_kinematics/builds/549009395

**Comment by Levi-Armstrong** [comment]
@gavanderhoorn This should be ready to be merged.

**Pull request merged**
