### PR TITLE
Updated CPack

### PR DESCRIPTION
**Pull request by marip8**
Use updated `cpack` macro in the boilerplate tools

### CODE REVIEW

**Comment by Levi-Armstrong** [comment]
Does this still generate the archive version (zip)?

**Comment by Levi-Armstrong** [comment]
Ah, I see now you move the cpack code to ros_industrial_cmake_boiler_plate. This is another package we could upgrade to using colcon like what we did in boost_plugin_loader for ubuntu and windows. We could also copy the CI scrips for uploading the archives.

**Comment by marip8** [comment]
It would be a good idea to revamp the CI process to be ROS independent and to add the workflows for generating and uploading debians. We can do that in a separate PR. Also, I just removed the 0.2.16 tag of the boilerplate tools, so this PR won't work until we release that

**Comment by Levi-Armstrong** [comment]
> It would be a good idea to revamp the CI process to be ROS independent and to add the workflows for generating and uploading debians. We can do that in a separate PR. Also, I just removed the 0.2.16 tag of the boilerplate tools, so this PR won't work until we release that

Yea, a separate PR sounds good.

**Review by Levi-Armstrong — APPROVED** [review]

**Comment by Levi-Armstrong** [comment]
@marip8 Is this good to merge?

**Comment by marip8** [comment]
Yes, now that 0.2.16 on the boilerplate tools exists

**Pull request merged**
