### PR TITLE
Add travis based on industrial_ci

### PR DESCRIPTION
**Pull request by simonschmeisser**
Surprisingly on this setup all tests succeed while they all fail on our internal CI or on my local pc ...

This could be extended to do more advanced stuff like clang-format, clang-tidy etc

### CODE REVIEW

**Comment by gavanderhoorn** [comment]
Any particular reason to use `moveit_ci`?

**Comment by simonschmeisser** [comment]
no, it was simple to copy paste, that's the whole reason

**Comment by simonschmeisser** [comment]
@gavanderhoorn would you prefer industrial_ci or something independent and minimal?

**Comment by gavanderhoorn** [comment]
I'm not *the* maintainer here, but seeing as we use `industrial_ci` in all other repositories that have CI setup, I think I'd like to keep things consistent and use `industrial_ci` here as well.

> [..] and minimal?

Setup for `industrial_ci` is pretty concise actually I believe:

```yaml
sudo: required
dist: trusty
language: generic

cache:
  directories:
    - $HOME/.ccache

git:
  quiet: true

env:
  global:
    - CCACHE_DIR=$HOME/.ccache
    - ROS_REPO=ros
  matrix:
    - ROS_DISTRO=kinetic
    - ROS_DISTRO=kinetic ROS_REPO=ros-shadow-fixed

install:
  - git clone --quiet --depth=1 https://github.com/ros-industrial/industrial_ci.git .ci_config

script:
  - .ci_config/travis.sh
```

**Comment by simonschmeisser** [comment]
sure, I'll test that later on

by "minimal" I was refering more to having an external dependency (*_ci) vs calling cmake directly as this code seems to be rather standalone. I agree on aiming for consistency thou

**Comment by simonschmeisser** [comment]
@gavanderhoorn @Jmeyer1292  industrial_ci successfully builds and runs the tests, please squash on merge

**Comment by gavanderhoorn** [comment]
Seeing as this is @Jmeyer1292's repository and Travis is not enabled for this repository I'll leave review and merging to @Jmeyer1292.

**Comment by simonschmeisser** [comment]
I added a small fix that makes the tests succeed on my system as well

**Comment by gavanderhoorn** [comment]
@simonschmeisser wrote:
> please squash on merge

@Levi-Armstrong: I believe you missed this.

**Comment by gavanderhoorn** [comment]
Could consider a force-push after a rebase to squash things.

**Comment by simonschmeisser** [comment]
It's fine this way, having the auto vs Vector and the missing eigen dependency in,  separate commits also make sense. Thanks for merging!

**Comment by Levi-Armstrong** [comment]
@gavanderhoorn Sorry missed your comment about squashing.

**Pull request merged**
